services:
  mysql:
    image: mysql:latest
    container_name: mysql_transporte
    ports:
      - "3308:3306"
    network_mode: bridge
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./db-scripts/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql