spring:
  application:
    name: prueba-sintad
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate.format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3308/db_sintad
    username: root
    password: 123456
token:
  rest:
    api: apis-token-9712.9oxWxBURarm9cA0g1ON4QXNgkeA86j-W
jwt:
  secret: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXo0NTY3ODkw

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    csrf:
      enabled: true
    path: /swagger-ui.html